carts/urls.py
from django.urls import path
from .views import cart_home, cart_update, checkout_home, checkout_done_view


app_name = 'carts'

urlpatterns = [
    path('', cart_home, name='home'),
    path('checkout/success/', checkout_done_view, name='success'),
    path('checkout/', checkout_home, name='checkout'),
    path('update/', cart_update, name='update'),
]

ecommerce/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.views import LogoutView

from django.contrib import admin
from django.urls import path, include
from accounts.views import login_page, register_page, guest_register_view
from addresses.views import checkout_address_create_view, checkout_address_reuse_view

from .views import home_page, about_page, contact_page


urlpatterns = [
    path('', home_page, name='home'),
    path('about/', about_page, name='about'),
    path('contact/', contact_page, name='contact'),
    path('login/', login_page, name='login'),
    path('register/', register_page, name='register'),
    path('register/guest/', guest_register_view, name='guest_register'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('admin/', admin.site.urls),
    path('cart/', include("carts.urls")),
    path('products/', include("products.urls")),
    path('search/', include("find.urls")),
    path('checkout/address/create/', checkout_address_create_view, name='checkout_address_create'),
    path('checkout/address/reuse/', checkout_address_reuse_view, name='checkout_address_reuse'),
]

if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

find/urls.py
from django.urls import path
from .views import FindProductView


app_name = 'find'
urlpatterns = [
    path('', FindProductView.as_view(), name='query'),
]

products/urls.py
from django.urls import path
from .views import ProductListView, ProductDetailView

app_name = 'products'
urlpatterns = [
    path('', ProductListView.as_view(), name='list'),
    path('<slug:slug>/', ProductDetailView.as_view(), name='detail'),
]

templates/base/navbar.html
{% url 'products:list' as product_list_url %}
{% url 'carts:home' as cart_home %}
{% url 'login' as login_url %}
{% url 'register' as register_url %}
{% url 'contact' as contact_url %}
{% url 'about' as about_url %}
{% url 'home' as home_url %}

<nav class="navbar navbar-expand-lg navbar-dark bg-dark mb-3">
   <div class='container'>
  <a class="navbar-brand" href="#">
    <img src="https://image.flaticon.com/icons/svg/25/25231.svg" width="30" height="30" class="d-inline-block align-top" alt="">
    eCommerce
  </a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item {% if request.path == home_url %}active{% endif %}">
        <a class="nav-link" href="{{ home_url }}">Home</a>
      </li>
      <li class="nav-item {% if request.path == about_url %}active{% endif %}">
        <a class="nav-link" href="{{ about_url }}">About</a>
      </li>
      <li class="nav-item {% if request.path == contact_url %}active{% endif %}">
        <a class="nav-link" href="{{ contact_url }}">Contact</a>
      </li>
      <li class="nav-item {% if request.path == product_list_url %}active{% endif %}">
        <a class="nav-link" href="{{ product_list_url }}">Products</a>
      </li>
      <li class="nav-item {% if request.path == cart_home %}active{% endif %}">
        <a class="nav-link" href="{{ cart_home }}">Cart</a>
      </li>

      {% if request.user.is_authenticated %}
       <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Account
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="#">Home</a>
          <a class="dropdown-item" href="#">Billing</a>
          <a class="dropdown-item" href="#">History</a>
          <a class='dropdown-item' href='#'>Library</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="{% url 'logout' %}">Logout</a>
        </div>
      </li>
      {% else %}
       <li class="nav-item {% if request.path == register_url %}active{% endif %}">
        <a class="nav-link" href="{{ register_url }}">Register</a>
      </li>
      <li class="nav-item {% if request.path == login_url %}active{% endif %}">
        <a class="nav-link" href="{{ login_url }}">Login</a>
      </li>
      {% endif %}
    </ul>
    {% include 'find/snippets/search-form.html' %}
  </div>
</div>
</nav>